### ISSUE TITLE
pNES on PS4: sound is not centered

### ISSUE THREAD

**Issue by hippie68** [Cpasjuste/pemu#97] opened 2022-01-20 22:47 UTC
The current PS4 port of pNES has a sound balance issue. The sound is not centered but louder on the right side. Very noticeable when wearing headphones.

**Comment by Cpasjuste** [comment] 2022-01-21 19:31
Hi,

I did take a closer look today (and updated nestopia to latest source) and I think the problem is still there and it's probably from nestopia. But too me it seems the difference is very minor. We'll see if it's better for you in the next update.

**Comment by hippie68** [comment] 2022-04-10 23:05
I just tried the current version (5.2), and the problem is still there. As before, the sound is much, much louder on the right side. It is an extreme difference.

**Comment by Cpasjuste** [comment] 2022-05-09 14:57
Hi,

Sorry but after a lot of debug i'm not able to fix the problem. I think/guess it comes from nestopia and won't be fixed anytime soon... closing the issue!

**Closed by Cpasjuste** 2022-05-09 14:57 UTC
