### ISSUE TITLE
 Intermittent stuttering is felt on psnes 6.3

### ISSUE THREAD

**Issue by brunohwas** [Cpasjuste/pemu#179] opened 2022-05-09 14:08 UTC
hello. We are very happy that this update has resolved the sound issue. However, there seems to be intermittent stuttering that was not felt in the previous version. (Super Mario RPG) Maybe it's because I switched from sx os to kefir. thank you so much.

And I have one more question. How do you use turbo mode?

**Comment by Vecinagamer** [comment] 2022-05-09 14:44
¿Cómo se usa el modo turbo?,,yes please.....

**Comment by tanaduda** [comment] 2022-05-09 20:57
> hello. We are very happy that this update has resolved the sound issue. However, there seems to be intermittent stuttering that was not felt in the previous version. (Super Mario RPG) Maybe it's because I switched from sx os to kefir. thank you so much.
> 
> And I have one more question. How do you use turbo mode?
Bug confirmed in TMNT IV. 

Graphics issue too

**Comment by brunohwas** [comment] 2022-05-10 02:37
I tested it a bit more and the stuttering feels better when using effects.

**Comment by Cpasjuste** [comment] 2022-05-11 10:31
Hi,

Could you guys test this psnes version? It should work as before. I did had a new option "AUDIO_SYNC" (which was enabled by default on latest versions): setting "AUDIO_SYNC" to "ON" will synchronize fps to audio, which should be the preferred method. If you feel some slowdowns but that's because it's like on real hardware, but audio will be perfect without stuttering. Setting it to "OFF" (default now) will run at a constant fps, but minor audio stuttering is present (like before i guess).
[psnes.zip](https://github.com/Cpasjuste/pemu/files/8669088/psnes.zip)
.

**Comment by Cpasjuste** [comment] 2022-05-11 12:28
Hi, should be fixed in [v6.4](https://github.com/Cpasjuste/pemu/releases/tag/v6.4) (currently building/uploading), will reopen the issue if it's not the case.

**Closed by Cpasjuste** 2022-05-11 12:28 UTC
Labels: SWITCH

**Comment by tanaduda** [comment] 2022-05-11 15:33
Yes, fixed now. Confirmed.

**Comment by brunohwas** [comment] 2022-05-13 05:13
> [안녕하세요, v6.4](https://github.com/Cpasjuste/pemu/releases/tag/v6.4) (현재 빌드/업로드 중) 에서 수정되어야 하며 그렇지 않은 경우 문제를 다시 엽니다.

oh thank you so much
