### ISSUE TITLE
Pgen 6.3 switch

### ISSUE THREAD

**Issue by mcbeth1935** [Cpasjuste/pemu#183] opened 2022-05-10 05:45 UTC
I was playing on my switch and i found some grafics issues, for example in the game of aladin when i attack sometimes the screen turns white for a second  and in the game demons of asterborg when i go back with the character the screen can't move and the character appears from the other side of the screen 
![20220510_004912](https://user-images.githubusercontent.com/105265145/167557232-48f83424-3cfe-4793-9beb-d8a4b361b9c8.jpg)
![20220510_004739](https://user-images.githubusercontent.com/105265145/167557318-2031e021-2581-44e1-bd2c-afc6a1f056d1.jpg)

**Comment by mcbeth1935** [comment] 2022-05-11 16:15
@Cpasjuste thank you so much for the updates, i have tested the emulator pgen 6.4 and still the same issues

**Comment by Cpasjuste** [comment] 2022-05-11 16:20
Hi,

Yes didn't had the time to check. If the issue is not marked as fixed and it's not in the changelog then it's not done yet!

**Comment by mcbeth1935** [comment] 2022-05-11 16:45
thank you so much for answering me, i will be grateful if you could solve this issue when you have time

**Comment by Cpasjuste** [comment] 2022-05-12 09:17
Hi @mcbeth1935 , the problem in "Demons of asterborg" is fixed and will be ready for next release.
For Aladdin, after some research, it seems to be intentional from the developers, see https://www.atari-forum.com/viewtopic.php?t=34189&start=200

> The quick white flashes are supposed to happen in Aladdin. If you swing your sword at the same time a guard does, you "clash" off of each other, and you get the screen flash along with a "ting" sound.

**Comment by MayanKoyote** [comment] 2022-05-13 07:09
Great!
Will this also fix the very first logo that is visible when the Demons of Asterborg game starts? White and turquoise Neofid Studios.

**Closed** 2022-05-21 15:50 UTC
Labels: bug, SWITCH, fixed

**Comment by MayanKoyote** [comment] 2022-05-25 03:51
Looks like v6.5 fixed the issue with the first animated logo. Thank you.
