### ISSUE TITLE
favorites.xml, adding a favorite game

### ISSUE THREAD

**Issue by angomania** [Cpasjuste/pemu#200] opened 2022-05-14 16:32 UTC
After I selected a filtered game (for example: Filter_Rating) to add it to my favorites, pEmus told me its already a favorite.
Almost all all filtered games are displayed as favorites.
I have to deselect the filtered game as a favorite and add it back as a favorite so it is saved in the favorite.xml.

**Comment by angomania** [comment] 2022-05-15 14:14
Very strange ... that only happens if a "favorites.xml" is created/present in the root dir. (for example only one game as favorite)
Then many games are marked as favorites if you press the "add/remove favorite button". Even if no filter is set (Only "Show Available" is set in settings).

**Comment by Cpasjuste** [comment] 2022-05-16 10:34
Hi @angomania,

I'm not able to reproduce the problem it seems. Is it possible that you were using a "pre-6.x" "favorites.xml" (games id changed in one of the 6.x version and could cause some problems). 
Else, do you have an emulator and specific game to reproduce the problem ?

**Comment by angomania** [comment] 2022-05-16 11:56
Here are the steps to reproduce:
- Clean download and unpack of Win pFbneo v6.4
- Copy "roms" folder to root of pFbneo
- Start pBneo. Main options: Show Available
- Add "´88 Games" to favorite (X Button)
- In gamelist scroll two games down, press X Button to add game "10-Yard Fight", following window is popping up:
![1](https://user-images.githubusercontent.com/16779776/168581842-1e947e3a-8740-42f7-97e2-4bc033b8d397.jpg)

The window to remove the favorite appears for almost every game in the list.
Although only a single game (see above: "88 Games") was saved in the favorites list. 

Tested all windows emulators. 
This only happens to pFbeno arcade games ("roms" folder). Others seem to be ok (tested Megadrive and Nes roms).
Also pSnes has this problem.

**Comment by Cpasjuste** [comment] 2022-06-09 13:02
Hi @angomania , this should be fixed in next release. Thanks for the report one more time!

**Closed** 2022-09-08 10:42 UTC
Labels: bug, fixed
