### ISSUE TITLE
Psnes cant see roms.

### ISSUE THREAD

**Issue by dzhonlevon** [Cpasjuste/pemu#237] opened 2022-11-23 18:16 UTC
Downloaded https://archive.org/details/no-intro-nintendo-super-nintendo-entertainment-system-20170529. Extracted to psnes/rom
Everybody say I need db.xml. There no  more switch files, only [psnes.nro]. Tried xml from windows psnes, tryed db.xml from old version from other sites. Saves db in switch, psnes, roms. No roms in avaliable. Please help. I dont like retro arch graphic
Mail: dzhon.levon@bk.ru

**Comment by Cpasjuste** [comment] 2023-03-17 13:21
Hi, the database is now embedded in the nro, so you should not need to do anything else. Also, i can't reproduce your problem here, are you sure your roms are located here: "/switch/psnes/roms/" ?

I'm closing this as i think it's an user problem (if not, feel free to reply here).

**Closed by Cpasjuste** 2023-03-17 13:21 UTC
