### ISSUE TITLE
Vita pSNES - showing all file extensions

### ISSUE THREAD

**Issue by npaladin2000** [Cpasjuste/pemu#128] opened 2022-03-21 13:32 UTC
I'm seeing every file in the programmed ROM directory, including PCMs, SRMs, etc etc. Any way to filter it to just ROMs and ZIPs?

**Comment by Cpasjuste** [comment] 2022-03-21 21:29
Hi,

Thanks for the report, I'll take a look asap.

**Comment by Cpasjuste** [comment] 2022-03-22 09:31
Hi,

This is fixed in https://github.com/Cpasjuste/pemu/commit/f86c485f24483ccd0ca8e330d8b1d1cdffd0118c and will be available for next release. Thanks for the report.

**Comment by Cpasjuste** [comment] 2022-05-05 14:42
Hi,

I think this should be fixed in [version 6.0](https://github.com/Cpasjuste/pemu/releases/tag/v6.0), can you confirm this ?

**Comment by robpinheiro** [comment] 2022-05-06 19:31
Something very strange is happening.
I updated psnes to version 6.0(the same occour with 6.1) to test and the following problem happens (remember I excludes the skin folder and the gamelist.xml file).
Every time I try to open the psnes on vita it crashes, I did some tests and I noticed that this is because of the games in the roms folder.
In my Roms folder are the zip files, if I remove all the roms it opens, if I put my msu games it opens, if I extract all the zip files it works, but if the games are compressed psnes crashes and doesn't open.

**Comment by Cpasjuste** [comment] 2022-05-06 20:01
Hi,

It would be really (really) useful for me if you could find which zipped file(s) does make the app crash so I can reproduce it.

**Comment by robpinheiro** [comment] 2022-05-06 20:59
I was wrong about the extracted roms working. lol
I'm sorry.
I performed new tests and found a rom that causes the error in psnes 6.0 and 6.1.
If you test it on psnes 5.2 it will work perfectly.
Attached is one of the roms I identified that causes the error
[2020 Super Baseball.zip](https://github.com/Cpasjuste/pemu/files/8643583/2020.Super.Baseball.zip)

**Comment by robpinheiro** [comment] 2022-05-06 21:00
For example with these attached it works normally, both in 5.2 and in 6.0 and 6.1

[7th Saga.zip](https://github.com/Cpasjuste/pemu/files/8643588/7th.Saga.zip)
[90 Minutes - European Prime Goal.zip](https://github.com/Cpasjuste/pemu/files/8643589/90.Minutes.-.European.Prime.Goal.zip)
[3 Ninjas Kick Back.zip](https://github.com/Cpasjuste/pemu/files/8643590/3.Ninjas.Kick.Back.zip)

**Comment by Cpasjuste** [comment] 2022-05-06 21:01
Many thanks for your time, will take a look tomorrow.

**Comment by Cpasjuste** [comment] 2022-05-07 05:02
Hi guys,

Thanks for the files @robpinheiro , this was very helpful (saved me a lot of time). As you can see here i think the problem is fixed (will also fix the vita platform): https://github.com/Cpasjuste/pemu/issues/153
I'll try to do a release this week-end.

**Comment by robpinheiro** [comment] 2022-05-07 14:13
> Oi pessoal,
> 
> Obrigado arquivos pelos@robpinheiro, isso foi muito útil (me economizou muito tempo). Como você pode ver aqui eu acho que o problema foi corrigido nesta semana (também irá alterar a plataforma): #153 Vou tentar fazer um lançamento final nesta semana.

Thanks friend, I'm glad I helped.  you are the best.

> Hi guys,
> 
> Thanks for the files @robpinheiro , this was very helpful (saved me a lot of time). As you can see here i think the problem is fixed (will also fix the vita platform): #153 I'll try to do a release this week-end.

Thanks friend, I'm glad I helped.  you are the best.

**Comment by joelsaacks** [comment] 2022-05-08 19:22
Thanks. I was just about to ask about why the VITA crashes with my big rom folder. Hopefully you manage to release a new vita version soon.

**Comment by Cpasjuste** [comment] 2022-05-08 20:47
Hi, should be fixed in [6.2](https://github.com/Cpasjuste/pemu/releases/tag/v6.2) (currently building, files will be available soon). If not, be sure to report here and i'll re-open the issue.

**Closed by Cpasjuste** 2022-05-08 20:47 UTC
Labels: bug, confirmed
