### ISSUE TITLE
The sound of The Legend of Zelda: A Link to the Past on psnes 5.2 was a little bouncy.

### ISSUE THREAD

**Issue by brunohwas** [Cpasjuste/pemu#131] opened 2022-03-23 12:44 UTC
Hello. thank you. The sound of The Legend of Zelda: A Link to the Past on psnes 5.2 was a little bouncy. And how to use turbo mode? Thank you for always.

**Comment by Cpasjuste** [comment] 2022-03-23 12:52
Hi, what is the system you are experiencing this (vita, switch, PS4) ?

**Comment by brunohwas** [comment] 2022-03-23 13:19
This is the nintendo switch version. I just checked and it seems that Final Fantasy 6 also has symptoms.

**Comment by brunohwas** [comment] 2022-03-23 13:19
This is the nintendo switch version. I just checked and it seems that Final Fantasy 6 also has symptoms.

**Comment by brunohwas** [comment] 2022-03-23 13:37
in frame palette changes

> Hi, what is the system you are experiencing this (vita, switch, PS4) ?

This is the nintendo switch version. I just checked and it seems that Final Fantasy 6 also has symptoms.

**Comment by Vecinagamer** [comment] 2022-03-24 16:26
Final Fantasy 6 also has symptoms switch nintendo

**Comment by Cpasjuste** [comment] 2022-03-27 09:01
Hi,

Could you guys try [this binary](http://files.mydedibox.fr/cpasjuste/dev/switch/pemu/psnes-5.2-audiofix.zip) to see if the problem is fixed ? Thanks.

**Comment by Cpasjuste** [comment] 2022-03-28 10:21
Hi,

Could you guys try [this binary](http://files.mydedibox.fr/cpasjuste/dev/switch/pemu/psnes-5.2-audiofix.zip) to see if the problem is fixed ? Thanks.

**Comment by brunohwas** [comment] 2022-03-28 17:08
> 안녕,
> 
> [이 바이너리](http://files.mydedibox.fr/cpasjuste/dev/switch/pemu/psnes-5.2-audiofix.zip) (오른쪽 클릭 > 다운로드)를 사용하여 문제가 해결되었는지 확인할 수 있습니까 ? 감사 해요.

Audiofix version does not work. At first, after the big psnes logo came out, only a black screen appeared. I am using sx os.

**Comment by brunohwas** [comment] 2022-03-28 17:10
> 안녕,
> 
> [이 바이너리](http://files.mydedibox.fr/cpasjuste/dev/switch/pemu/psnes-5.2-audiofix.zip) (오른쪽 클릭 > 다운로드)를 사용하여 문제가 해결되었는지 확인할 수 있습니까 ? 감사 해요.

The original 5.2 version worked fine.

**Comment by Vecinagamer** [comment] 2022-03-28 18:58
Audiofix version does not work

**Comment by Cpasjuste** [comment] 2022-05-05 14:42
Hi,

I think this should be fixed in [version 6.0](https://github.com/Cpasjuste/pemu/releases/tag/v6.0), can you confirm this ?

**Comment by Cpasjuste** [comment] 2022-05-08 20:28
Hi, should be fixed in [6.2](https://github.com/Cpasjuste/pemu/releases/tag/v6.2) (currently building, files will be available soon). If not, be sure to report here and i'll re-open the issue.

**Closed by Cpasjuste** 2022-05-08 20:28 UTC
Labels: bug, confirmed
