### ISSUE TITLE
PGEN 7z and CHD files unreadable

### ISSUE THREAD

**Issue by RinMaru** [Cpasjuste/pemu#171] opened 2022-05-08 23:38 UTC
7z Megadrive and gamegear roms aren't recognized and while Sega CD CHD games show up in ALL filter, none will play. is this a bug or a dependency not yet covered?

**Comment by Cpasjuste** [comment] 2022-05-09 07:27
Hi @RinMaru,

7z support is not natively supported in Genesis Plux GX and so won't be supported soon in pgen.
For CHD games, i need to implement that, will do that asap.

**Comment by Cpasjuste** [comment] 2022-05-09 08:25
Hi,

CHD support was added in latest code, will be available in next release.

**Comment by RinMaru** [comment] 2022-05-09 17:45
> Pgen 6.3 roms mega cd,,doesn't load them,,I have them in their folders just like megadrive works,,,master-system works,,game gear works,,,mega-cd doesn't work

do you have bios_CD_U.bin in the bios folder?

**Comment by tanaduda** [comment] 2022-05-09 18:27
> Pgen 6.3 roms mega cd,,doesn't load them,,I have them in their folders just like megadrive works,,,master-system works,,game gear works,,,mega-cd doesn't work

PGEN doesnt crash for you while opening?

**Comment by Cpasjuste** [comment] 2022-05-10 07:34
Hi,

For me the problem is solved (except 7z support Wich is not planned yet), closing the issue!

**Closed by Cpasjuste** 2022-05-10 07:34 UTC
Labels: enhancement, todo

**Comment by eiflax** [comment] 2025-09-09 21:40
just tried now current actual version on ps4. Sega Mega CD chd files are not detected. Am I missing some extra detail ?
