### ISSUE TITLE
VITA: PGEN 6.2 Filters do not work

### ISSUE THREAD

**Issue by RinMaru** [Cpasjuste/pemu#169] opened 2022-05-08 22:18 UTC
changing game filters dont seem to work and the only way to get games to show up is by using ALL filter. Mega drive games show up in its filter but CD and gg fail to show anything unless all is used

**Comment by Cpasjuste** [comment] 2022-05-09 06:16
Hi,

Are you using zipped files for roms (for mega-cd, images needs to be unzipped for now)?

**Comment by Cpasjuste** [comment] 2022-05-09 09:17
Hi,

This should be fixed in next release, but keep in mind that "pemu" emulators ports are mean to be used with specific romset (see https://github.com/Cpasjuste/pemu/tree/master/pgen)

**Comment by Cpasjuste** [comment] 2022-05-09 14:54
Hi, this should be fixed in [6.3](https://github.com/Cpasjuste/pemu/releases/tag/v6.3) (currently uploading), if not be sure to report here so i re-open the issue.

**Comment by RinMaru** [comment] 2022-05-09 17:17
its fixed for the most part but now official gamegear and genesis games dont show up only game hacks and my mega cd games show up

**Comment by Cpasjuste** [comment] 2022-05-09 19:40
Crap, reopening the issue, will try to take a look tomorrow.

**Comment by Cpasjuste** [comment] 2022-05-10 06:59
Hi @RinMaru , i'm unable to reproduce your problem, i do see all my zipped games in gg and md filtering (with the specified romsets in the [readme](https://github.com/Cpasjuste/pemu/tree/master/pgen)).

**Comment by Cpasjuste** [comment] 2022-05-10 08:15
Both zipped and unzipped files show fine for me (supported extensions for md, gg and sms are ".zip", ".md", ".smd", ".gen", ".bin", ".mdx", ".sms", ".gg", ".sg", ".68k")

**Comment by RinMaru** [comment] 2022-05-10 08:20
> Both zipped and unzipped files show fine for me (supported extensions for md, gg and sms are ".zip", ".md", ".smd", ".gen", ".bin", ".mdx", ".sms", ".gg", ".sg", ".68k")

Not showing up heremaybe a way for users to read whats not in the sets would be an option somehow

**Comment by RinMaru** [comment] 2022-05-10 08:32
> Hi @RinMaru , i'm unable to reproduce your problem, i do see all my zipped games in gg and md filtering (with the specified romsets in the [readme](https://github.com/Cpasjuste/pemu/tree/master/pgen)). 
> 
> 
> 

Are they supposed to be zipped i unzipped them all and all games are in md format and they aren't showing up ill just zip them all and close this.

**Comment by MayanKoyote** [comment] 2022-05-10 12:20
I did a little research in case of SMD games.
List of SMD games is in [gamelist.xml] file (https://github.com/Cpasjuste/pemu/blob/master/pgen/data/common/romfs/gamelist.xml)
for example Mega Man - The Wily Wars:
```
    <game id="462">
        <path>Mega Man - The Wily Wars (Europe).zip</path>
        <name>Mega Man - The Wily Wars</name>
        <desc>Mega Man: Wily Wars is a collection of the first three NES Mega Man titles. It features enhanced graphics and  sound as well as the game "Wily Tower", a short game that mixes enemies from all three games.</desc>
        <rating>0.85</rating>
        <releasedate>19940101T000000</releasedate>
        <developer id="31">Capcom</developer>
        <publisher id="31">Capcom</publisher>
        <genre>Platform</genre>
        <genreid>7</genreid>
        <players>1</players>
        <cloneof>0</cloneof>
        <system id="1" parentid="0">Megadrive</system>
        <image type="mixrbv2">media/mixrbv2/Mega Man - The Wily Wars (Europe).png</image>
        <video type="video">media/video/Mega Man - The Wily Wars (Europe).mp4</video>
    </game>
```
It turns out that the emulator wants to see the game in a zip archive, with the name Mega Man - The Wily Wars (Europe).zip

Doing testing:
Mega Man - The Wily Wars (Europe).zip - visible
Mega Man - The Wily Wars (Europe).md - invisible (though Mega Man - The Wily Wars (Europe).md it's what is really inside of zip archive)
Mega Man - The Wily Wars (Europe).bin - visible

**Comment by Cpasjuste** [comment] 2022-05-10 13:37
You'll only get description and such for zipped files (the ones in the gamelist.xml, which comes from the romsets specified in the readme). But "unknown" roms (as your unzipped .md files) should be visible. Are you using v6.3 ?

**Comment by MayanKoyote** [comment] 2022-05-11 07:17
> But "unknown" roms (as your unzipped .md files) should be visible. Are you using v6.3?
> Here ".md" files are visible.

Yes, it's v6.3. *.md are not visible for me:
![2022-05-11-01](https://user-images.githubusercontent.com/43220515/167791137-afc19162-a1ba-467c-b6e7-bd4d4f755fe8.jpg)
![2022-05-11-02](https://user-images.githubusercontent.com/43220515/167791171-45fb6816-0ad1-4277-9623-e3bbbc600de7.jpg)
![2022-05-11-03](https://user-images.githubusercontent.com/43220515/167791201-55b2f4a0-7de7-4d31-aaca-a7a607d45fbc.jpg)
![2022-05-11-04](https://user-images.githubusercontent.com/43220515/167791219-284345a9-374c-4eb2-a443-239c6d447a47.jpg)

**Comment by Cpasjuste** [comment] 2022-05-11 10:34
Ok, to be fair i didn't test on vita, only on linux. Will take a closer look asap.

**Comment by Cpasjuste** [comment] 2022-05-11 13:42
Hi, this is finally fixed (only affecting consoles like vita/switch). Will be available in next release.

**Comment by MayanKoyote** [comment] 2022-05-11 15:12
Hello. Thank you very much for this.
In my case, my roms are not always "fresh" from the internet. Some may be from ancient times, some may be edited or patched. So they are not always stored in archives or exactly in zip.
By the way, today I played with the memory manager for Sega CD in the form of an .iso image, it turned out that the emulator does not see * .ISO in the megacd/ folder, but sees * .iso. It's good that I remembered that it could be case sensitive, otherwise I had already started writing .cue for this image.

**Closed** 2022-05-12 08:38 UTC
Labels: bug, VITA, fixed
